#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ ! -d ".legit" ]; then
	echo "$filename: error: no .legit directory containing legit repository exists"
	exit 1
fi
if [ $# -eq 0 ]; then
	echo "usage: "$filename" <filenames>" 
	exit 1
fi 

for file in "$@" 
do
	files=$(echo "$file" | egrep "[^a-zA-Z0-9._-]")	
	#echo $files	
	if [ ! -z $files ]; then	
		echo ""$filename": error: invalid filename '"$file"'"
		exit 1
	fi
done

for file in "$@"
do
	
	if [ ! -f  "$file" ]; then
		if [ -f ".legit/add/"$file"" ]; then
			rm .legit/add/"$file"
		else	 			
			echo ""$filename": error: can not open '"$file"'"
			exit 1
		fi
	fi

		
done
for file in "$@"
do
	if [ -f "$file" ]; then 		
		cp $file .legit/add
	fi
done
