#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ ! -d ".legit" ]; then
	echo "$filename: error: no .legit directory containing legit repository exists"
	exit 1
elif [ -z "$(ls -A .legit/commit)" ]; then
	echo "$filename: error: your repository does not have any commits yet"
	exit 1
else
	cat .legit/commit/commit_history.txt | cut -d' ' --complement -f1 | sort -r
fi
