#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ ! -d ".legit" ]; then
	echo "$filename: error: no .legit directory containing legit repository exists" >&2
	exit 1
fi
branch=`cat .legit/current_branch`
if [ $# -eq 0 ]; then
	echo "usage: "$filename" <filenames>" >&2
	exit 1
fi 

for file in "$@" 
do
	files=$(echo "$file" | egrep "[^a-zA-Z0-9._-]")	
	#echo $files	
	if [ ! -z $files ]; then	
		echo ""$filename": error: invalid filename '"$file"'" >&2
		exit 1
	fi
done
branch=`cat .legit/current_branch`
#echo $branch

for file in "$@"
do
	
	if [ ! -f  "$file" ]; then
		if [ -f ".legit/"$branch"/add/"$file"" ]; then
			rm .legit/"$branch"/add/"$file"
		else	 			
			echo ""$filename": error: can not open '"$file"'" >&2
			exit 1
		fi
	fi

		
done
for file in "$@"
do
	if [ -f "$file" ]; then 		
		cp "$file" .legit/"$branch"/add
	fi
done
