#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ ! -d ".legit" ]; then
	echo "$filename: error: no .legit directory containing legit repository exists" >&2
	exit 1
fi
branch=`cat .legit/current_branch`
if [ $# -le 1 ]; then
	echo "usage: "$filename" [-a] -m commit-message" >&2 
	exit 1

elif [ $# -eq 3 ]  && ( [ $1  != "-a" ] || [ ! $2  = "-m" ] ) ; then
	echo "usage: "$filename" [-a] -m commit-message" >&2
	exit 1
elif [ $# -eq 2 ]  && [ $1  != "-m" ]; then
	echo "usage: "$filename" [-a] -m commit-message" >&2
	exit 1
fi



if  [ -f ".legit/"$branch"/commit/commit_history.txt" ]; then
		
	commit=$(egrep commit .legit/"$branch"/commit/commit_history.txt | cut -d' ' -f2 | tail -1)		
else
	touch commit_history.txt	
	mv commit_history.txt .legit/"$branch"/commit	
	#echo "nah"	
	
fi

if [ -z $commit ]; then
	commit=-1
fi

if [ $1 = "-a" ]; then
	for file in *; do
		if [ -f .legit/"$branch"/add/"$file" ]; then
			cp "$file" .legit/"$branch"/add	
		fi		
	done
commitmessage=$3;
else
	commitmessage=$2;		
fi

if [ -z "$commitmessage" ]; then
	echo "usage: "$filename" [-a] -m commit-message" >&2
	exit 1
fi

if [ $commit -ge 0 ]; then
	dir="commit_$commit"
	testvariable=$(diff .legit/"$branch"/commit/"$dir" .legit/"$branch"/add ) 	
	if [ -z  "$testvariable" ]; then
		echo "nothing to commit"
		exit 0	
	fi
elif [ -z "$(ls -A .legit/"$branch"/add)" ]; then
	echo "nothing to commit"
	exit 0 
fi
commit=$(( commit+1 ))

	
mkdir .legit/"$branch"/commit/"commit_"$commit""
if [ ! -z "$(ls -A .legit/"$branch"/add)" ]; then
	cp ".legit/"$branch"/add"/* .legit/"$branch"/commit/"commit_"$commit""
fi
echo -n "commit $commit $commitmessage\\n" >>.legit/"$branch"/commit/commit_history.txt
echo "Committed as commit "$commit""
