#!/usr/bin/perl -w

use File::Basename;
use File::Copy::Recursive qw(fcopy rcopy dircopy fmove rmove dirmove);
use File::Path;
# Checkout use snapshot save and load! 
$legit = '.legit';
$filename = basename($0);

if (! -d $legit){

	print STDERR "$filename: error: no .legit directory containing legit repository exists\n";
	exit 1;
}
$branch=getBranch();

my @files = glob("./.legit/$branch/commit/*");
@files or (print STDERR "$filename: error: your repository does not have any commits yet\n" and exit 1);

$delete = 0;	
if (!@ARGV){

	listBranches();
	exit 0;	
}
elsif ($ARGV[0] =~ /^-d/){

	$delete = 1;
	shift @ARGV;	
}


$inputbranch = $ARGV[0];	

if($inputbranch =~ /[^a-zA-Z0-9_-]/){
	print STDERR "$filename: error: invalid branch name '$inputbranch'\n";
	exit 1;
}elsif($inputbranch =~ /^[0-9]+$/){
	print STDERR "$filename: error: invalid branch name '$inputbranch'\n";
	exit 1;
}

if (@ARGV>1 or $inputbranch =~ /^-/){
	print STDERR "usage: $filename [-d] <branch>\n";
	exit 1;
}


if ($delete == 1){

	deleteBranch($inputbranch);
}else
{

	createBranch($inputbranch);
}

sub getBranch{

	open $F, '<' , ".legit/current_branch";
	my $branch=<$F>;
	close $F;
	return $branch;

}

sub listBranches{

	open $F, '<', ".legit/branches";
	my @branches=<$F>;
	close $F;
	@branches = sort @branches;
	print @branches;

}

sub createBranch{
	
	my ($create) = @_;
	if (-d ".legit/$create"){
		print STDERR "$filename: error: branch \'$create\' already exists\n";
		exit 1;
	}else{
		mkdir ".legit/$create";
		#mkdir "$create"._wd;
		open $F, '>>', ".legit/branches";
		print $F $create;
		print $F "\n";
		close $F;
		rcopy(".legit/$branch", ".legit/$create");			
		#rcopy("$branch"._wd, "$create"._wd);
	}
	
}

sub deleteBranch{

	my ($destroy) = @_;
	if (! -d ".legit/$destroy"){
		print STDERR "$filename: error: branch \'$destroy\' does not exist\n";
		exit 1;
	}elsif ( "$destroy" eq "master"){
		print STDERR "$filename: error: can not delete branch \'$destroy\'\n";
		exit 1;
	}
	rmtree ".legit/$destroy";
	#$wd = "$destroy"._wd;
	#rmtree "$wd";
	open $F, '<', ".legit/branches";
	my @array = <$F>;
	close $F;
	@array or die;	
	open $F, '>', ".legit/branches";
	foreach $line (@array){
		chomp($line);		
		if ("$line" eq "$destroy"){
			next;		
		}
		print $F $line;
		print $F "\n";	
	}
	close $F;
	print "Deleted branch \'$destroy\'\n"
}
