#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ $# -ne 0 ]; then
	echo "usage: "$filename"" 
	exit 1
fi
if [ -d ".legit" ]; then

	echo "$filename: error: .legit already exists"
	exit 1
fi
mkdir -p ".legit"
echo "Initialized empty legit repository in .legit"
