#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ ! -d ".legit" ]; then
	echo "$filename: error: no .legit directory containing legit repository exists"
	exit 1
fi

if [ $# -eq 0 ]; then
	echo "usage: "$filename" [-a] -m commit-message" 
	exit 1
fi

if [ ! -d ../.legit/index ]; then
	echo "nothing to commit"
	exit 1
fi
