#!/bin/dash

filename="`echo "$0" | rev | cut -d'/' -f1 | rev `"

if [ ! -d ".legit" ]; then
	echo "$filename: error: no .legit directory containing legit repository exists"
	exit 1
fi

if [ $# -le 1 ]; then
	echo "usage: "$filename" [-a] -m commit-message" 
	exit 1

elif [ $# -eq 3 ]  && ( [ $1  != "-a" ] || [ ! $2  = "-m" ] ) ; then
	echo "usage: "$filename" [-a] -m commit-message" 
	exit 1
elif [ $# -eq 2 ]  && [ $1  != "-m" ]; then
	echo "usage: "$filename" [-a] -m commit-message" 
	exit 1
fi



if  [ -f ".legit/commit/commit_history.txt" ]; then
		
	commit=$(egrep commit .legit/commit/commit_history.txt | cut -d' ' -f2 | tail -1)		
else
	touch commit_history.txt	
	mv commit_history.txt .legit/commit	
	#echo "nah"	
	
fi

if [ -z $commit ]; then
	commit=-1
fi

if [ $1 = "-a" ]; then
	for file in *; do
		if [ -f .legit/add/"$file" ]; then
			cp $file .legit/add	
		fi		
	done
commitmessage=$3;
else
	commitmessage=$2;		
fi

if [ $commit -ge 0 ]; then
	dir="commit_$commit"
	testvariable=$(diff .legit/commit/"$dir" .legit/add ) 	
	if [ -z  "$testvariable" ]; then
		echo "nothing to commit"
		exit 1	
	fi
elif [ -z "$(ls -A .legit/add)" ]; then
	echo "nothing to commit"
	exit 1 
fi
commit=$(( commit+1 ))

	

mkdir .legit/commit/"commit_"$commit""
cp .legit/add/* .legit/commit/"commit_"$commit""
echo -n "commit $commit $commitmessage\\n" >> .legit/commit/commit_history.txt
echo "Committed as commit "$commit""
